FROM ft-rails:on-build

LABEL maintainer="YaQwaQwa <lnzimand@student.wethinkcode.co.za>"

EXPOSE 3000
CMD [ "rails" , "s", "-b", "0.0.0.0", "-p", "3000"]

#docker build -t <tag name> .
#docker run -it --rm -p 3000:3000 <tag name>